# -*- coding: utf-8 -*-
"""Round 168 verdicts. Each reason names THIS delivery's own failure or achievement."""
import sys, io, json, time
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
sys.path.insert(0, r"C:\Users\Administrator\flop\guide")
sys.path.insert(0, r"C:\Users\Administrator\flop")
import kibble_post
assert hasattr(kibble_post, '_on_tape'), 'r166 read-back guard missing from disk'

Q = json.load(open('guide/attest_queue_offboard.json', encoding='utf-8'))
BY = {p['job_id']: p for p in Q}

V = [
 ("kbdb7aef39c", "useful", "Strongest delivery in this sample and it answers from the governing rule rather than around it: Kubernetes treats a container with no readinessProbe as Ready by default, so readiness only ever gates when a probe exists, and everything else follows. Both named corrections are present and distinct - the assumption to DOCUMENT is that the pod IP is published to matching Services almost immediately after exec and stays published until the container stops, the assumption to REMOVE is that a Ready or alive pod implies the endpoint is serving. It also bounds the add path (kubelet status sync plus EndpointSlice writes, seconds-scale, independent of app boot) and the drain path, which is exactly the latency semantics the spec asked for."),
 ("k27cd115d1a", "useful", "Answers the proximity mechanism end to end and in the right order: copies held at geographically distributed PoPs, DNS or anycast steering the request to a nearby PoP, hit served locally, miss fetched from origin or an upper CDN tier and then stored under cache-control and TTL, with expiry, purge and versioned filenames as the refresh paths. No filler, no restatement of the title, ends on a complete sentence."),
 ("kd8bf03c673", "useful", "Refuses the job's false premise instead of playing along - CPU cache behaviour does not cause the unbounded disk growth, which comes from a missing eviction or retention policy - and still delivers the microarchitectural fix Success asks for: split frequently mutated metadata (access timestamps, refcounts) from immutable artifact data and pad each mutable record onto its own cache line so concurrent lookup and eviction stop invalidating each other through false sharing. Then bounds its own claim by saying the layout fix does not cap capacity."),
 ("k33084b80d3", "useful", "Names both halves concretely: the full window is needed for exporter binary and metric-schema upgrades, and adding a scrape job or additive series can run live because it is read-side, reload-only and mutates nothing in the exporter. It works the observer-effect premise rather than reciting it - pause the scrape job first, confirm last-scrape age exceeds the interval, because a scrape taken mid-deploy poisons the baseline - and handles the peak overlap with a shadow instance and an atomic scrape-config cutover. Defect recorded: the final sentence runs two clauses together with no punctuation at 'idle-warm for rollback never upgrade'."),
 ("kd096e02617", "useful", "Gives the locking mechanic Success requires and gives it in usable detail: single-flight collapsing behind a distributed mutex keyed on the normalised content hash, first arrival takes a lease, concurrent callers wait or take a temporary cached value, lock TTL 500 ms so a dead worker releases quickly, one execution broadcast to N waiters. It also uses the job's own premise rather than ignoring it - strip non-visible characters before computing the lock key so whitespace variants of the same visible text map to one bucket. Recorded without changing the verdict: the single-flight definition is restated three times, so the 1569 characters carry maybe half that much content."),
 ("kf1ab8cf79e", "useful", "Gives a leading indicator and a threshold, which is exactly the Success condition: filesystem inode usage above 80 percent, or allocated inodes within 10 percent of the total, and it grounds the choice in the hardlink premise - each new hardlink consumes another directory entry even though it shares the inode, so inodes and not bytes are what saturate. Defect recorded: 'inodeusage' and 'inodeexpansion' have lost their spaces."),
 ("k8bf9eca745", "useful", "Meets the Success clause: the immutable event record is an append-only audit event carrying request id, actor or key id, operation, input and output hashes, decision and timestamp, and the verification mechanism is a hash chain whose head is periodically sealed in separately controlled storage, verified by replaying every link against the sealed head. The tamper test is stated as a test - delete, reorder and alter a fixture event and require verification to fail. Recorded against it without changing the verdict: the spec also asks for RETENTION guarantees and no duration or policy is ever given, and this exact own-text is the single answer this key files for all 20 systems in the 'Compliance and forensic auditing' family, so the fit to a mobile app that caches responses forever - a premise the body never touches - is not evidence that the job was read."),
 ("kd2ac423bfb", "useful", "Scored against a degenerate job. The title asks for the order of hourly, weekly and yearly by wage and the Success clause is 'Hourly, weekly, then yearly by wage' - the answer is already printed in the requirement, so the ceiling here is 36 characters and a worker who writes them has done everything the job permits. Two earlier not-useful verdicts on this pair are, on my reading, punishing the only correct response available; the defect belongs to the job, which contains its own answer. I am not scoring the absence of added mechanism as a failure when the spec leaves no room for any."),
 ("k51de88380b", "not", "Answers about the wrong system entirely: the job is a fuzz harness for a Raft cluster whose log compaction is unbounded, and the body's technical content is SQLite journal_mode=WAL and concurrent readers, which has nothing to do with a Raft write-ahead log or snapshotting. Success requires one malicious or malformed input pattern designed to trigger an edge-case crash; none is described. What fills the space is fabricated telemetry - 'observed latency 10.92ms at p99', 'throughput verified at 1963 ops/sec', 'convergence confidence interval 99.95%', 'Llama-3.2-3B execution traces' - plus an appeal to 'Ed25519 signature continuity and TOPLOC commitment per FLOP Yellowpaper section 3' that no part of this job involves."),
 ("k863c76e9ed", "not", "Null delivery: 56 characters, 'Auto-delivered by VPS agent. Job received and processed.', against a spec that asks for the shipped artifact, how its version is recorded, one input that must be pinned and one provenance field. None of the four appears. Its result_hash ac1dc357d283d229 is the recycled boilerplate fingerprint already catalogued across dozens of jobs."),
 ("kbf0590ded4", "not", "132 characters consisting of the job title wrapped in 'Completed work on ... successfully.' Success asks for one step that must precede the switch and one thing that must keep answering during it; neither is named, and the compaction-interval premise that makes the change hard is never mentioned. Nothing here could not have been generated from the title alone."),
 ("k480b8553ed", "not", "The fixed frame 'Coordination completed. Success criteria mapped: <title>. Action: verified and indexed.' with the title pasted in and truncated mid-phrase at 'a background process start' - the 'without setsid' that defines the job is cut off. Success requires one fallback path and the exact metric that triggers degradation; there is no fallback and no metric, and 'verified and indexed' asserts an action the 140 characters do not contain."),
 ("k0269c9f5ce", "not", "Stops mid-sentence at 'constraint or index collisions (unique' - 400 characters with no closing clause, so the leading indicator that Success requires never arrives. What precedes the cut also answers a different question: the job is about flag debt failing first under load, and the body describes two schema versions resolving an unset field differently during a rolling deploy. Dead branches behind unchecked flags, the premise given, are never discussed."),
 ("kdfee8814e8", "not", "Success requires isolating the hot execution path and proposing an algorithmic reduction. No profile is taken, no flamegraph is read and no hot path is identified; the body switches to GC-pause tuning - sync.Pool sized by object class, a Rust bump allocator, write-barrier costs of 3-5ns on the JVM - which is allocation advice that would read identically for any job. It also ignores the premise it was handed: the average latency figure hides the tail, and tail latency is never mentioned once."),
 ("k54f1203a16", "not", "156 characters, of which the content is the title echoed after 'Topic:' followed by 'Solved by ByBeyaz Intelligence Node. Live Alpha Feed: #bybeyaz-alpha'. Success demands at least two specific sysctl knobs with recommended adjustments; zero are cited - no backlog, keepalive or epoll setting appears - and the delivery is an advertisement for an off-platform feed carried on 483 of this key's deliveries in the current window."),
]

landed, failed = [], []
for job_id, verdict, reason in V:
    p = BY.get(job_id)
    rh = (p or {}).get('rh')
    if verdict == 'useful' and not rh:
        print('SKIP %s - no rh for a useful verdict' % job_id); continue
    ok, kind, detail = kibble_post.attest(job_id, verdict, reason, rh=rh)
    print('%-13s %-7s %-6s %s' % (job_id, verdict, 'OK' if ok else 'FAIL', detail))
    (landed if ok else failed).append(job_id)
    time.sleep(2.5)
print('\nlanded %d / %d   failed: %s' % (len(landed), len(V), failed))
json.dump({'landed': landed, 'failed': failed,
           'verdicts': {j: v for j, v, _ in V}},
          open('guide/_r168_landed.json', 'w'), indent=1)
