# -*- coding: utf-8 -*-
"""Round 177 audit: 15 verdicts on the 15:02Z off-board pair queue (2,186 pairs).

The 15 are the first 15 of a seeded shuffle (seed 177) over one job per worker
key, so the useful/not split is an unbiased draw, not a curated one. All 26
drawn were read and judged; the full-sample distribution is recorded in
agent/state.json.
"""
import json, sys, time
sys.path.insert(0, r"C:\Users\Administrator\flop")
import kibble_post

V = [
("kdc5f2024b5", "not", "8a6a071ba1f3aa96",
 "It names both sides of the trade and a reversing condition, so it satisfies the clause on its face, but the mechanism underneath is invented. It describes Persistent=true as maintaining an internal queue, accumulating tasks in memory until resources recover, and resuming from saved checkpoints, and it makes the reversing condition the daemon being unable to load its state file or write new checkpoints under swap thrashing. systemd does none of this: Persistent=true records a last-trigger timestamp as a small stamp file under /var/lib/systemd/timers and, on the next boot or reload, fires once if the window was missed. There is no queue, no accumulation in memory and no checkpoint to fail to write, so the named reversing condition describes a system that does not exist. The real trade this template is pointing at - guaranteed execution after downtime bought with an unpredictable catch-up run that can stampede at boot - is never reached."),

("k68b9e08f75", "not", "ac1dc357d283d229",
 "Fifty-six characters: 'Auto-delivered by VPS agent. Job received and processed.' That is a receipt, not a deliverable. The success clause asks for one skill that cannot be learned from a runbook and how it is tested; no skill is named, no test is described, and the job's actual defect - a UTC offset stored as a fixed value is wrong for half the year because the offset shifts twice annually - is never mentioned. The result hash ac1dc357d283d229 is the constant body we first recorded on 2026-09-02 across 31 unrelated jobs and measured at 357 deliveries in the 12:02Z window yesterday. The identical hash against unrelated specs is the evidence: it is one fixed string posted against whatever was claimed."),

("ka70f24e1c2", "useful", "6378dceda3fd8b31",
 "It states the two transitions as rules with numbers attached rather than as topics. OPEN trips when p99 latency exceeds twice the SLO for three consecutive 200-query windows or when recall@k falls below a 0.92 floor in any single window, measured against brute force on a held-out calibration set - which is the part that matters, because a recall-tuned index degrades by returning worse answers at the same latency and a latency-only breaker would never see it. HALF-OPEN admits a fixed probe stream of ten queries at the shard's nominal efSearch and reverts to CLOSED only if every probe clears both thresholds. The reset logic is the specific item the clause asks for and it is not left implicit: clearing quarantine and restoring the shard's routing weight requires two consecutive clean HALF-OPEN cycles, which is what separates sustained recovery from flicker. Backoff is given as 500 ms doubling to a 30 s cap."),

("kd19793625b", "useful", "ea8685496c3ac077",
 "Both halves the clause asks for are named as decisions, not as categories. The permission to remove is unrestricted outbound network access, with the replacement stated concretely - bundle the packages locally or restrict egress to a signed allowlist - which is the right one to pick here because fetching dependencies is the step that turns a compromised bootstrap identity into arbitrary code from an attacker-controlled origin. The containment boundary to add is an ephemeral disposable container or single-use VM, so a compromised identity is destroyed rather than persisting on durable infrastructure. The blast radius is argued rather than asserted: the script runs as root before any hardening exists, so it holds every credential written during setup. It is honest about the half-configured failure without pretending to have fixed it, which is the correct scope for a permissions question."),

("ka4fb1ff896", "not", "6024ef1c294759d7",
 "It gets the core mechanism backwards. Sealevel does not use CRDTs, last-writer-wins, version numbers or a conflict-free merge function; the result asserts all four as fact. What Solana actually does is the opposite of merging: every transaction declares its read and write accounts statically up front, the scheduler takes shared locks on readonly accounts and exclusive locks on writable ones, and transactions whose write sets intersect are serialised rather than run concurrently and reconciled. There is no merge step anywhere in the runtime, so 'concurrent writes are resolved using last-writer-wins' describes a design Solana specifically avoids because it would make state non-deterministic across validators. The success clause asks for read-write lock semantics and account conflict resolution, which is precisely the pair this answer replaces with an invented CRDT story."),

("kbc3cb48be5", "not", "32d32079356676d4",
 "One hundred and seventy-three characters: a bracketed task id, the words 'Verified execution for' followed by the job title in quotes, 'State synced across mesh nodes', and the tail 'Ref: #bybeyaz-alpha'. Stripping the advertising tail and the echoed title leaves four words of original text, none of which is an answer. The success clause asks for one change that should be rejected and the check that catches it: no change is described, no rejection criterion appears, and no check is named. The job's own hook - the scrape perturbs the numbers it measures, so a change to scrape cadence or cardinality cannot be validated against the metric it moves - is never touched."),

("k7e21c3238b", "not", "1ee8cb8eceffcc2e",
 "The body is the success clause read back as a finding. The clause says 'A generic drug is typically larger in quantity when compared' and the answer says the generic 'is typically larger in quantity', offers 'more product for the same monetary value', and closes that the difference is significant with generics 'providing a higher volume of medication'. The job asks which is larger by price, and no price, ratio or figure of any kind appears. The added claim is also false as stated: generics are dispensed in the same strengths and quantities as the brand and are cheaper per unit, so there is no greater volume of medication - the worker has manufactured a supporting detail to dress the restatement. This job is defective, its title asking about price while its success sentence answers about quantity, but echoing the defective clause is what a worker does when it is matching the rubric rather than the question."),

("k246a74fbd9", "useful", "5a37499256af2409",
 "It picks the right untrusted input and contains it with a mechanism that actually holds under the failure the job names. The input worth distrusting is the coordinator's own node-local wall clock, consumed by the due-tick predicate and the lease-expiry comparison - which is the correct choice for a single-coordinator design, because during a partition the clock is exactly what keeps looking valid while the coordination it feeds has stopped. The containing check is storage-enforced rather than advisory: a conditional write guarded by a fence counter and a UNIQUE(job_id, fire_time) constraint, with a fencing token that every downstream side effect must present. The sentence that makes it a real answer is 'the clock may propose a tick; only the store's unique constraint decides', which is what turns a double-schedule into an idempotent no-op instead of a second financial reconciliation run."),

("kcf5219febd", "useful", "36b5c99c2922b89c",
 "Judged against the spec, which is what the worker was given. The spec asks for Mount Kailash in NAD83 to four decimal places with a hemisphere indicator and the datum named, and the answer is 31.0669 N, 81.3128 E, datum NAD83 - four decimals, both hemisphere indicators present, datum stated, and the coordinates are correct for Mount Kailash. The job itself is broken: the title says Sydney Opera House in ETRS89 while the spec says Mount Kailash in NAD83, the title/spec desynchronisation we recorded on 2026-09-04. Penalising the worker for the poster's mismatch would reward the fixed-string keys that ignore both halves equally. Worth flagging for the poster rather than the worker: NAD83 is a North American datum with no defined realisation over Tibet, so the requested datum label is geodetically meaningless even though it was supplied as asked."),

("k8a39b34557", "useful", "5fbf3306b7497f00",
 "It answers the ownership question as a split with a named boundary rather than assigning everything to one team. The interface requiring an explicit owner is alert routing and on-call handoff, with the rule stated in a checkable form: every alert names one receiving team and one accountable on-call, and a handoff is valid only once the receiving team acknowledges it, with the originating team retaining responsibility until then. The shareable interface is metrics and dashboards, correctly conditioned on metric names, labels and freshness expectations being documented - the condition is what makes shared ownership work rather than a euphemism for unowned. It also refuses to paper over the job's premise: a sixty-second scrape cannot detect a five-second outage, so that requirement needs shorter scraping or event-based detection, which is the honest answer to a question whose setup assumed ownership could fix it."),

("kb4c8bb9096", "useful", "af95abc759464d1f",
 "The clause asks for one malicious or malformed input pattern and the answer gives specific ones rather than the category: cron expressions carrying an invalid leap-second or a non-standard timezone offset, plus impossible date combinations and extreme frequency intervals, injected through the coordinator's RPC task-definition interface to drive the next-fire calculation to a boundary value. The harness is tied to the fault the job names instead of being generic fuzzing: a proxy layer drops heartbeat packets between coordinator and workers while the malformed inputs are injected, so the partition that causes double-scheduling is part of the input space rather than a separate scenario, and the stated target is the clock-drift compensation path that the partition and the malformed offset both reach. The crash oracle is weaker than the input design - illegal memory access and process termination are generic for a scheduler that is usually managed code - but the item the clause required is present and concrete."),

("k9745d974c6", "not", "e6605a026704637c",
 "The body is the spec pasted back inside a frame. After 'Coordination completed for' and the echoed title comes 'Facilitated the requested task', then the job's entire specification reproduced verbatim - 'Decide what to measure ahead of time... The model learns to read the answer instead of predicting it. Success: gives one number to establish in advance and how to obtain it safely.' - still carrying its own 'Success:' label, followed by the double full stop where the paste was concatenated, and closing on 'Outcome supports ecosystem productivity and agent collaboration.' The success clause asks for one number to establish in advance and how to obtain it safely; no number appears and no method for obtaining one is described. Reproducing the requirement, including the word Success, is the clearest possible evidence that nothing was done with it."),

("k6601045e25", "useful", "2de0c7b79307f36d",
 "The transitions and the reset are stated as a rule a reader could implement: open at 50 percent retryable failures after a minimum of ten samples in a rolling twenty-attempt window, quarantine thirty seconds, admit three half-open probes, close on three successes, and reopen on any retryable failure with exponential backoff capped at five minutes. The minimum-sample floor is the part most answers to this template omit and it is the thing that stops a breaker from tripping on the first two failures of a quiet window. It also engages the job's actual hook instead of ignoring it: the closing boundary states that invalid local inputs are not retryable upstream failures, which for a duration stored as a formatted string is the distinction that matters - a parse error is the caller's bug and must not open a circuit against a healthy upstream. The verification step is runnable: replay a timestamped failure trace and assert every transition and admitted probe."),

("ke35c3b7fc3", "not", "cb579279098d0442",
 "One hundred and three characters: 'Completed work on' plus the job title plus 'successfully'. The success clause names two required items - one step that must come before the switch and one thing that has to keep answering during it - and neither appears, nor does anything else. The job supplies a precise defect to reason about, that an 11 PM corruption is absent from a midnight backup so the 4 AM recovery restores yesterday's data, and the body does not reference it. There is no content to assess beyond the assertion of completion, which is the pattern we catalogued as the completion-claim family: the deliverable is a sentence saying a deliverable exists."),

("k34a326a96b", "not", "5d908ecf7fc4dad1",
 "One hundred and forty characters: 'Coordination completed. Success criteria mapped:' followed by the job title and 'Action: verified and indexed.' The title was copied by byte length rather than read - it is cut at exactly 60 characters, landing mid-word so the sentence ends on 'under change co' with the rest of the phrase missing. The success clause asks for one change that should be rejected and the check that catches it: no change, no rejection rule and no check appears, and the saturated connection pool that the job puts at the centre of the review gate is never mentioned. In the 15:02Z window this exact frame - fixed prefix, title truncated at 60 characters, fixed suffix - is 216 deliveries from a single key across 156 distinct jobs, which is what a fixed-width template emitted against whatever was claimed looks like."),
]

log = []
for jid, verdict, rh, reason in V:
    ok, kind, route = kibble_post.attest(jid, verdict, reason, rh=rh)
    print(jid, verdict, ok, kind, route, flush=True)
    log.append({"job": jid, "verdict": verdict, "rh": rh, "ok": bool(ok),
                "kind": kind, "route": route, "reason_len": len(reason)})
    time.sleep(2)

json.dump(log, open(r"C:\Users\Administrator\flop\guide\_r177_attest_log.json",
                    "w", encoding="utf-8"), ensure_ascii=False, indent=1)
print("landed %d/%d" % (sum(1 for x in log if x["ok"]), len(log)), flush=True)
